# linear and angular speed limits for the robot
# best combo 1.5, 0.4
max_v: 1.5 #0.9 #1.5 #0.4 # m/s # average waypoint metric distance (meter/point) * RATE when recording (point/second)
max_w: 0.4 #0.8 #0.8 # rad/s
# observation rate fo the robot
frame_rate: 4 # Hz
graph_rate: 0.3333 # Hz  

set_height: -3

# topic names (modify for different robots/nodes)
vel_teleop_topic: /cmd_vel_mux/input/teleop 
vel_navi_topic: /cmd_vel_mux/input/navi
vel_recovery_topic: /cmd_vel_mux/input/recovery
vel_lang_topic: /cmd_vel_mux/input/lang