twist_mux:
  # default publishes to cmd_vel
  topics: 
  #subscribed topics
      - name: "gnm vels"
        topic: "/cmd_vel_mux/input/navi"
        timeout: 0.5
        priority: 1
        short_desc: "The default cmd_vel, controllers unaware that we are multiplexing cmd_vel should come here"
      - name: "teleop"
        topic: "/cmd_vel_mux/input/teleop"
        timeout: 0.5
        priority: 2
        short_desc: "Navigation stack controller"
      - name: "gnm recovery"
        topic: "/cmd_vel_mux/input/recovery"
        timeout: 0.1
        priority: 1
      - name: "lang"
        topic: "/cmd_vel_mux/input/lang"
        timeout: 0.5
        priority: 3
        short_desc: "Language-based controller"

  locks: []