project_name: vint-release
run_name: vint-5c
# load_run: vint-release/vint-5c_2023_11_14_21_53_56
# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 1
epochs: 100
gpu_ids: [0]
num_workers: 1
lr: 5e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: vint
obs_encoder: "efficientnet-b0" # by default, this is imagenet pretrained
obs_encoding_size: 512
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
late_fusion: False

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5
# tradeoff between action and distance prediction loss
alpha: 0.5

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 0
  max_dist_cat: 10
close_far_threshold: 10 # distance threshold used to seperate the close and the far  subgoals that are sampled per datapoint

# action output params
len_traj_pred: 5
learn_angle: True

# dataset specific parameters
image_size: [85, 64] # width, height
goal_type: "image"

datasets:
  # go_stanford:
  #   data_folder: /mnt/efs/fs1/t2r/visualnav-transformer/go_stanford # datasets/stanford_go_new
  #   train: /mnt/efs/fs1/t2r/visualnav-transformer/train/vint_train/data/data_splits/go_stanford/train/
  #   test: /mnt/efs/fs1/t2r/visualnav-transformer/train/vint_train/data/data_splits/go_stanford/test/
  #   end_slack: 0
  #   goals_per_obs: 2 # increase dataset size
  #   negative_mining: True
  airsim_explore:
    data_folder: /home/jefferson/Desktop/T2R-Project/visualnav-transformer/datasets/airsim_explore # datasets/stanford_go_new
    train: /home/jefferson/Desktop/T2R-Project/visualnav-transformer/train/vint_train/data/data_splits/airsim_explore/train/
    test: /home/jefferson/Desktop/T2R-Project/visualnav-transformer/train/vint_train/data/data_splits/airsim_explore/test/
    end_slack: 0
    goals_per_obs: 2 # increase dataset size
    negative_mining: True

  # private datasets (uncomment if you have access)
  # seattle:
  #   data_folder: /home/<username>/vint_dataset/seattle/
  #   train: /home/<username>/data_splits/seattle/train/
  #   test: /home/<username>/data_splits/seattle/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True
  # scand:
  #   data_folder: /home/<username>/vint_dataset/scand/
  #   train: /home/<username>/data_splits/scand/train/
  #   test: /home/<username>/data_splits/scand/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True

# logging stuff
## =0 turns off
print_log_freq: 100 # in iterations
image_log_freq: 1000 #0 # in iterations
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 10 # in iterations
eval_freq: 1 # in epochs